spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: Rjz123,,,
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/powerup?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    maximumPoolSize: 3
    minimumIdle: 1
    connectionTestQuery: SELECT 1
    pool-name: AppPool
    auto-commit: true
    initialization-mode: always
    platform: mysql
  aop:
    proxy-target-class: true
  redis:
    host: 127.0.0.1
    port: 6379
    maxTotal: 200
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: 10000
    timeout: 0
